import { useCallback, useEffect, useState } from 'react'
import PageHeader from '@/components/common/PageHeader'
import Card from '@/components/ui/Card'
import SearchInput from '@/components/ui/SearchInput'
import ReportTable from '@/components/reports/ReportTable'
import ReportPreviewModal from '@/components/reports/ReportPreviewModal'
import ErrorState from '@/components/common/ErrorState'
import { useApi } from '@/hooks/useApi'
import { useDebounce } from '@/hooks/useDebounce'
import { ReportService } from '@/services/ReportService'
import { useToast } from '@/hooks/useToast'

export default function Reports() {
  const toast = useToast()
  const [search, setSearch] = useState('')
  const debouncedSearch = useDebounce(search, 300)
  const [page, setPage] = useState(1)

  const [previewId, setPreviewId] = useState(null)

  const fetchReports = useCallback(
    () => ReportService.list({ search: debouncedSearch, page, pageSize: 5 }),
    [debouncedSearch, page]
  )
  const { data, loading, error, refetch } = useApi(fetchReports)

  const fetchPreview = useCallback(() => (previewId ? ReportService.get(previewId) : Promise.resolve(null)), [
    previewId,
  ])
  const { data: previewReport, loading: previewLoading, refetch: refetchPreview } = useApi(fetchPreview, {
    immediate: false,
  })

  useEffect(() => {
    if (previewId) refetchPreview().catch(() => {})
  }, [previewId, refetchPreview])

  const handleDownload = (report) => {
    if (!report.summary) {
      toast.error('No report data available.')
      return
    }
    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>DentAI Report - ${report.patientName}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;color:#0f172a;padding:0 24px}
h1{color:#0f766e;border-bottom:2px solid #0f766e;padding-bottom:8px}
h3{color:#334155;margin-top:24px}p{color:#475569;line-height:1.6}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;color:#94a3b8;font-size:12px}</style></head>
<body><h1>DentAI Diagnostic Report</h1><p><strong>${report.patientName}</strong> · ${report.type} · ${new Date(report.date).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}</p>
${report.summary.split('\n').map(l => `<p>${l}</p>`).join('')}
<div class="footer">Generated by DentAI · dentai.vercel.app</div></body></html>`
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `DentAI-Report-${report.patientName.replace(/\s+/g, '-')}.html`
    a.click()
    URL.revokeObjectURL(url)
    toast.success(`Report downloaded for ${report.patientName}`)
  }

  return (
    <div>
      <PageHeader title="Reports" description="Search, filter, generate, and download clinical reports." />

      <Card>
        <Card.Header>
          <SearchInput
            value={search}
            onChange={(v) => {
              setSearch(v)
              setPage(1)
            }}
            placeholder="Search by patient…"
            className="max-w-xs"
          />
        </Card.Header>
        <Card.Body className="px-0 py-0">
          {error ? (
            <div className="px-3 py-3">
              <ErrorState title="Unable to load reports" message={error.message} onRetry={refetch} />
            </div>
          ) : (
            <div className="px-2">
              <ReportTable
                reports={data?.items ?? []}
                loading={loading}
                onView={(row) => setPreviewId(row.id)}
                onDownload={handleDownload}
                pagination={
                  data ? { page: data.page, pageCount: data.pageCount, onPageChange: setPage } : undefined
                }
              />
            </div>
          )}
        </Card.Body>
      </Card>

      <ReportPreviewModal
        isOpen={Boolean(previewId)}
        onClose={() => setPreviewId(null)}
        report={previewReport}
        loading={previewLoading}
      />
    </div>
  )
}
